server:
  port: 8761

spring:
  application:
    name: eureka-8761
eureka:
  instance:
    hostname: 192.168.1.164
    prefer-ip-address: true
    ip-address: 192.168.1.164
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info