server:
  port: 8761

spring:
  application:
    name: eureka-8761
eureka:
  instance:
    hostname: 192.168.1.164
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://192.168.1.164:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info